@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package icu.gensoukyo.neo_mystias_izakaya.compat;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;