package icu.gensoukyo.neo_mystias_izakaya.registry.item;

import icu.gensoukyo.neo_mystias_izakaya.NeoMystiasIzakaya;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;
import java.util.function.UnaryOperator;

public class NMIFoodItems {
    public static final List<DeferredItem<Item>> ITEM_LIST = new ArrayList<>();
    public static final DeferredRegister.Items ITEMS =
            DeferredRegister.createItems(NeoMystiasIzakaya.MODID);

    public static DeferredItem<Item> registerItem(
            DeferredRegister.Items register,
            String name,
            Function<Item.Properties, Item> func,
            UnaryOperator<Item.Properties> properties
    ) {
        DeferredItem<Item> item = register.registerItem(name, func, properties);
        ITEM_LIST.add(item);
        return item;
    }

    public static final DeferredItem<Item> AGAINST_THE_WORLD = registerItem(ITEMS, "food/against_the_world", Item::new, props -> props);
    public static final DeferredItem<Item> AGONY_ODEN = registerItem(ITEMS, "food/agony_oden", Item::new, props -> props);
    public static final DeferredItem<Item> ALL_MEAT_FEAST = registerItem(ITEMS, "food/all_meat_feast", Item::new, props -> props);
    public static final DeferredItem<Item> BAKED_SWEET_POTATO = registerItem(ITEMS, "food/baked_sweet_potato", Item::new, props -> props);
    public static final DeferredItem<Item> BAMBOO_MEAT_POT = registerItem(ITEMS, "food/bamboo_meat_pot", Item::new, props -> props);
    public static final DeferredItem<Item> BAMBOO_SPRING = registerItem(ITEMS, "food/bamboo_spring", Item::new, props -> props);
    public static final DeferredItem<Item> BEEF_BOWL = registerItem(ITEMS, "food/beef_bowl", Item::new, props -> props);
    public static final DeferredItem<Item> BEEF_WELLINGTON = registerItem(ITEMS, "food/beef_wellington", Item::new, props -> props);
    public static final DeferredItem<Item> BISCAY_BISCUITS = registerItem(ITEMS, "food/biscay_biscuits", Item::new, props -> props);
    public static final DeferredItem<Item> BOILED_TOFU = registerItem(ITEMS, "food/boiled_tofu", Item::new, props -> props);
    public static final DeferredItem<Item> BUDDHA_JUMPS_OVER_THE_WALL = registerItem(ITEMS, "food/buddha_jumps_over_the_wall", Item::new, props -> props);
    public static final DeferredItem<Item> BUDDHAS_DELIGHT = registerItem(ITEMS, "food/buddhas_delight", Item::new, props -> props);
    public static final DeferredItem<Item> BURN_OUT_PUDDING = registerItem(ITEMS, "food/burn_out_pudding", Item::new, props -> props);
    public static final DeferredItem<Item> CANDIED_SWEET_POTATO = registerItem(ITEMS, "food/candied_sweet_potato", Item::new, props -> props);
    public static final DeferredItem<Item> CANTONESE_CHAR_SIU = registerItem(ITEMS, "food/cantonese_char_siu", Item::new, props -> props);
    public static final DeferredItem<Item> CARVED_ROSE_SALAD = registerItem(ITEMS, "food/carved_rose_salad", Item::new, props -> props);
    public static final DeferredItem<Item> CAUTION_HELLISH_SPICE = registerItem(ITEMS, "food/caution_hellish_spice", Item::new, props -> props);
    public static final DeferredItem<Item> CEILING_LONGING_PIE = registerItem(ITEMS, "food/ceiling_longing_pie", Item::new, props -> props);
    public static final DeferredItem<Item> CHEESE_OMELETTE = registerItem(ITEMS, "food/cheese_omelette", Item::new, props -> props);
    public static final DeferredItem<Item> CLASSIC_STEAK = registerItem(ITEMS, "food/classic_steak", Item::new, props -> props);
    public static final DeferredItem<Item> CREAM_OF_MUSHROOM_SOUP = registerItem(ITEMS, "food/cream_of_mushroom_soup", Item::new, props -> props);
    public static final DeferredItem<Item> CREAMY_CRAB = registerItem(ITEMS, "food/creamy_crab", Item::new, props -> props);
    public static final DeferredItem<Item> CREAMY_VEGETABLE_CHOWDER = registerItem(ITEMS, "food/creamy_vegetable_chowder", Item::new, props -> props);
    public static final DeferredItem<Item> CRISPY_SPIRALS = registerItem(ITEMS, "food/crispy_spirals", Item::new, props -> props);
    public static final DeferredItem<Item> CUBIC_KEDAMA_ICE_CREAM = registerItem(ITEMS, "food/cubic_kedama_ice_cream", Item::new, props -> props);
    public static final DeferredItem<Item> CUBIC_KEDAMA_VOLCANIC_TOFU = registerItem(ITEMS, "food/cubic_kedama_volcanic_tofu", Item::new, props -> props);
    public static final DeferredItem<Item> DAIMYOS_FEAST = registerItem(ITEMS, "food/daimyos_feast", Item::new, props -> props);
    public static final DeferredItem<Item> DARK_MATTER = registerItem(ITEMS, "food/dark_matter", Item::new, props -> props);
    public static final DeferredItem<Item> DEEP_FRIED_SHRIMP_TEMPURA = registerItem(ITEMS, "food/deep_fried_shrimp_tempura", Item::new, props -> props);
    public static final DeferredItem<Item> DEEP_FRIED_TOFU = registerItem(ITEMS, "food/deep_fried_tofu", Item::new, props -> props);
    public static final DeferredItem<Item> DEW_RUNNY_EGGS = registerItem(ITEMS, "food/dew_runny_eggs", Item::new, props -> props);
    public static final DeferredItem<Item> DORAYAKI = registerItem(ITEMS, "food/dorayaki", Item::new, props -> props);
    public static final DeferredItem<Item> DRAGON_CARP = registerItem(ITEMS, "food/dragon_carp", Item::new, props -> props);
    public static final DeferredItem<Item> DRAGONSONG_PEACH = registerItem(ITEMS, "food/dragonsong_peach", Item::new, props -> props);
    public static final DeferredItem<Item> DRUNK_SHRIMP_IN_BAMBOO = registerItem(ITEMS, "food/drunk_shrimp_in_bamboo", Item::new, props -> props);
    public static final DeferredItem<Item> DUMPLINGS = registerItem(ITEMS, "food/dumplings", Item::new, props -> props);
    public static final DeferredItem<Item> EEL_BOWL_WITH_EGG = registerItem(ITEMS, "food/eel_bowl_with_egg", Item::new, props -> props);
    public static final DeferredItem<Item> EGGS_BENEDICT = registerItem(ITEMS, "food/eggs_benedict", Item::new, props -> props);
    public static final DeferredItem<Item> EIGHT_TRIGRAM_FISH_MAWS = registerItem(ITEMS, "food/eight_trigram_fish_maws", Item::new, props -> props);
    public static final DeferredItem<Item> ENERGY_PUDDING = registerItem(ITEMS, "food/energy_pudding", Item::new, props -> props);
    public static final DeferredItem<Item> ENERGY_SKEWER = registerItem(ITEMS, "food/energy_skewer", Item::new, props -> props);
    public static final DeferredItem<Item> FAINT_DREAM = registerItem(ITEMS, "food/faint_dream", Item::new, props -> props);
    public static final DeferredItem<Item> FALLING_BLOSSOMS = registerItem(ITEMS, "food/falling_blossoms", Item::new, props -> props);
    public static final DeferredItem<Item> FLOWING_SOMEN = registerItem(ITEMS, "food/flowing_somen", Item::new, props -> props);
    public static final DeferredItem<Item> FRESH_TOFU = registerItem(ITEMS, "food/fresh_tofu", Item::new, props -> props);
    public static final DeferredItem<Item> FRIED_CICADA_SLOUGHS = registerItem(ITEMS, "food/fried_cicada_sloughs", Item::new, props -> props);
    public static final DeferredItem<Item> FRIED_LAMPREYS = registerItem(ITEMS, "food/fried_lampreys", Item::new, props -> props);
    public static final DeferredItem<Item> FRIED_PORK_CUTLET = registerItem(ITEMS, "food/fried_pork_cutlet", Item::new, props -> props);
    public static final DeferredItem<Item> FUJIS_LAVA = registerItem(ITEMS, "food/fujis_lava", Item::new, props -> props);
    public static final DeferredItem<Item> GIANT_TAMAGOYAKI = registerItem(ITEMS, "food/giant_tamagoyaki", Item::new, props -> props);
    public static final DeferredItem<Item> GLOOMY_FRUIT_PIE = registerItem(ITEMS, "food/gloomy_fruit_pie", Item::new, props -> props);
    public static final DeferredItem<Item> GOLDEN_CRISPY_FISH_CAKES = registerItem(ITEMS, "food/golden_crispy_fish_cakes", Item::new, props -> props);
    public static final DeferredItem<Item> GOLDEN_RIBS_SOUP = registerItem(ITEMS, "food/golden_ribs_soup", Item::new, props -> props);
    public static final DeferredItem<Item> GOLDEN_TWO_SHROOM_WRAP = registerItem(ITEMS, "food/golden_two_shroom_wrap", Item::new, props -> props);
    public static final DeferredItem<Item> GRILLED_LAMPREY = registerItem(ITEMS, "food/grilled_lamprey", Item::new, props -> props);
    public static final DeferredItem<Item> HEART_THROBBING_SURPRISE = registerItem(ITEMS, "food/heart_throbbing_surprise", Item::new, props -> props);
    public static final DeferredItem<Item> HEART_WARMING_CONGEE = registerItem(ITEMS, "food/heart_warming_congee", Item::new, props -> props);
    public static final DeferredItem<Item> HODGEPODGE = registerItem(ITEMS, "food/hodgepodge", Item::new, props -> props);
    public static final DeferredItem<Item> HONEYED_CHESTNUT = registerItem(ITEMS, "food/honeyed_chestnut", Item::new, props -> props);
    public static final DeferredItem<Item> HOT_PEPPER_SOUP = registerItem(ITEMS, "food/hot_pepper_soup", Item::new, props -> props);
    public static final DeferredItem<Item> HOURAI_BRANCH = registerItem(ITEMS, "food/horai-dama_no_eda", Item::new, props -> props);
    public static final DeferredItem<Item> HUNTERS_CASSEROLE = registerItem(ITEMS, "food/hunters_casserole", Item::new, props -> props);
    public static final DeferredItem<Item> IMITATION_BEAR_PAW = registerItem(ITEMS, "food/imitation_bear_paw", Item::new, props -> props);
    public static final DeferredItem<Item> IMITATION_SHIRIKODAMA = registerItem(ITEMS, "food/imitation_shirikodama", Item::new, props -> props);
    public static final DeferredItem<Item> IMMORTAL_TURKEY = registerItem(ITEMS, "food/immortal_turkey", Item::new, props -> props);
    public static final DeferredItem<Item> INO_SHIKA_CHOU = registerItem(ITEMS, "food/ino_shika_chou", Item::new, props -> props);
    public static final DeferredItem<Item> INSTANTDEATH = registerItem(ITEMS, "food/instantdeath", Item::new, props -> props);
    public static final DeferredItem<Item> ITALIAN_RISOTTO = registerItem(ITEMS, "food/italian_risotto", Item::new, props -> props);
    public static final DeferredItem<Item> KABAYAKI_LAMPREYS = registerItem(ITEMS, "food/kabayaki_lampreys", Item::new, props -> props);
    public static final DeferredItem<Item> KABUTO_STEAMED_CAKE = registerItem(ITEMS, "food/kabuto_steamed_cake", Item::new, props -> props);
    public static final DeferredItem<Item> KAGUYA_HIME = registerItem(ITEMS, "food/kaguya_hime", Item::new, props -> props);
    public static final DeferredItem<Item> KITTEN_CANELE = registerItem(ITEMS, "food/kitten_canele", Item::new, props -> props);
    public static final DeferredItem<Item> KITTEN_PIZZA = registerItem(ITEMS, "food/kitten_pizza", Item::new, props -> props);
    public static final DeferredItem<Item> KITTENS_WATER_PLAY = registerItem(ITEMS, "food/kittens_water_play", Item::new, props -> props);
    public static final DeferredItem<Item> LIONS_HEAD = registerItem(ITEMS, "food/lions_head", Item::new, props -> props);
    public static final DeferredItem<Item> LITTLE_SWEET_POISON = registerItem(ITEMS, "food/little_sweet_poison", Item::new, props -> props);
    public static final DeferredItem<Item> LONG_HAIR_PRINCESS = registerItem(ITEMS, "food/long_hair_princess", Item::new, props -> props);
    public static final DeferredItem<Item> LOTUS_FISH_LAMPS = registerItem(ITEMS, "food/lotus_fish_lamps", Item::new, props -> props);
    public static final DeferredItem<Item> LUNAR_DANGO = registerItem(ITEMS, "food/lunar_dango", Item::new, props -> props);
    public static final DeferredItem<Item> LUNAR_LOVER_BISCUITS = registerItem(ITEMS, "food/lunar_lover_biscuits", Item::new, props -> props);
    public static final DeferredItem<Item> MAD_HATTERS_TEA_PARTY = registerItem(ITEMS, "food/mad_hatters_tea_party", Item::new, props -> props);
    public static final DeferredItem<Item> MAPO_TOFU = registerItem(ITEMS, "food/mapo_tofu", Item::new, props -> props);
    public static final DeferredItem<Item> MIASMA_GARDEN = registerItem(ITEMS, "food/miasma_garden", Item::new, props -> props);
    public static final DeferredItem<Item> MISERY_CHEESE_STICKS = registerItem(ITEMS, "food/misery_cheese_sticks", Item::new, props -> props);
    public static final DeferredItem<Item> MISO_TOFU = registerItem(ITEMS, "food/miso_tofu", Item::new, props -> props);
    public static final DeferredItem<Item> MOCHI = registerItem(ITEMS, "food/mochi", Item::new, props -> props);
    public static final DeferredItem<Item> MOLECULAR_EGG = registerItem(ITEMS, "food/molecular_egg", Item::new, props -> props);
    public static final DeferredItem<Item> MOON_CAKE = registerItem(ITEMS, "food/moon_cake", Item::new, props -> props);
    public static final DeferredItem<Item> MOONLIGHT_OVER_THE_LOTUS_POND = registerItem(ITEMS, "food/moonlight_over_the_lotus_pond", Item::new, props -> props);
    public static final DeferredItem<Item> MUSHROOM_HERB_ROAD = registerItem(ITEMS, "food/mushroom_herb_road", Item::new, props -> props);
    public static final DeferredItem<Item> MUSHROOM_MAIDENS_TIP_TAP_POT = registerItem(ITEMS, "food/mushroom_maidens_tip_tap_pot", Item::new, props -> props);
    public static final DeferredItem<Item> NATURES_BEAUTY = registerItem(ITEMS, "food/natures_beauty", Item::new, props -> props);
    public static final DeferredItem<Item> NEKO_MANMA = registerItem(ITEMS, "food/neko_manma", Item::new, props -> props);
    public static final DeferredItem<Item> NIGIRI_SUSHI = registerItem(ITEMS, "food/nigiri_sushi", Item::new, props -> props);
    public static final DeferredItem<Item> NITEN_ICHIRYU = registerItem(ITEMS, "food/niten_ichiryu", Item::new, props -> props);
    public static final DeferredItem<Item> OEDO_BOAT_FEAST = registerItem(ITEMS, "food/oedo_boat_feast", Item::new, props -> props);
    public static final DeferredItem<Item> OKONOMIYAKI = registerItem(ITEMS, "food/okonomiyaki", Item::new, props -> props);
    public static final DeferredItem<Item> ORDINARY_EAT_ME_CUPCAKE = registerItem(ITEMS, "food/ordinary_eat_me_cupcake", Item::new, props -> props);
    public static final DeferredItem<Item> ORIGIN_OF_LIFE = registerItem(ITEMS, "food/origin_of_life", Item::new, props -> props);
    public static final DeferredItem<Item> PALACE_OF_THE_HAN = registerItem(ITEMS, "food/palace_of_the_han", Item::new, props -> props);
    public static final DeferredItem<Item> PANCAKES_WITH_SYRUP = registerItem(ITEMS, "food/pancakes_with_syrup", Item::new, props -> props);
    public static final DeferredItem<Item> PEACH_BRAISED_PORK = registerItem(ITEMS, "food/peach_braised_pork", Item::new, props -> props);
    public static final DeferredItem<Item> PEACH_FLOWER_CRYSTAL_ROLL = registerItem(ITEMS, "food/peach_flower_crystal_roll", Item::new, props -> props);
    public static final DeferredItem<Item> PEACH_SHRIMP_SALAD = registerItem(ITEMS, "food/peach_shrimp_salad", Item::new, props -> props);
    public static final DeferredItem<Item> PEACH_TAPIOCA = registerItem(ITEMS, "food/peach_tapioca", Item::new, props -> props);
    public static final DeferredItem<Item> PEACH_YATSUHASHI = registerItem(ITEMS, "food/peach_yatsuhashi", Item::new, props -> props);
    public static final DeferredItem<Item> PICKLES = registerItem(ITEMS, "food/pickles", Item::new, props -> props);
    public static final DeferredItem<Item> PINE_NUT_CAKE = registerItem(ITEMS, "food/pine_nut_cake", Item::new, props -> props);
    public static final DeferredItem<Item> PINK_RICE_BALL = registerItem(ITEMS, "food/pink_rice_ball", Item::new, props -> props);
    public static final DeferredItem<Item> PLANET_MARS = registerItem(ITEMS, "food/planet_mars", Item::new, props -> props);
    public static final DeferredItem<Item> PLUM_TEA_RICE = registerItem(ITEMS, "food/plum_tea_rice", Item::new, props -> props);
    public static final DeferredItem<Item> PORK_BAMBOO_SHOOTS_STIR_FRY = registerItem(ITEMS, "food/pork_bamboo_shoots_stir_fry", Item::new, props -> props);
    public static final DeferredItem<Item> PORK_BOWL = registerItem(ITEMS, "food/pork_bowl", Item::new, props -> props);
    public static final DeferredItem<Item> PORK_MUSHROOM_STIR_FRY = registerItem(ITEMS, "food/pork_mushroom_stir_fry", Item::new, props -> props);
    public static final DeferredItem<Item> PORK_RICE_BALL = registerItem(ITEMS, "food/pork_rice_ball", Item::new, props -> props);
    public static final DeferredItem<Item> PORK_STIR_FRY = registerItem(ITEMS, "food/pork_stir_fry", Item::new, props -> props);
    public static final DeferredItem<Item> PORK_TROUT_KEBAB = registerItem(ITEMS, "food/pork_trout_kebab", Item::new, props -> props);
    public static final DeferredItem<Item> POTATO_CROQUETTES = registerItem(ITEMS, "food/potato_croquettes", Item::new, props -> props);
    public static final DeferredItem<Item> POWER_SOUP = registerItem(ITEMS, "food/power_soup", Item::new, props -> props);
    public static final DeferredItem<Item> PURE_WHITE_LOTUS = registerItem(ITEMS, "food/pure_white_lotus", Item::new, props -> props);
    public static final DeferredItem<Item> RAINBOW_PAN_FRIED_PORK_BUNS = registerItem(ITEMS, "food/rainbow_pan_fried_pork_buns", Item::new, props -> props);
    public static final DeferredItem<Item> REAL_SEAFOOD_MISO_SOUP = registerItem(ITEMS, "food/real_seafood_miso_soup", Item::new, props -> props);
    public static final DeferredItem<Item> RED_BEAN_DAIFUKU = registerItem(ITEMS, "food/red_bean_daifuku", Item::new, props -> props);
    public static final DeferredItem<Item> RICE_BALL = registerItem(ITEMS, "food/rice_ball", Item::new, props -> props);
    public static final DeferredItem<Item> RICE_POWDER_MEAT = registerItem(ITEMS, "food/rice_powder_meat", Item::new, props -> props);
    public static final DeferredItem<Item> ROASTED_MUSHROOM = registerItem(ITEMS, "food/roasted_mushroom", Item::new, props -> props);
    public static final DeferredItem<Item> SAKURA_PUDDING = registerItem(ITEMS, "food/sakura_pudding", Item::new, props -> props);
    public static final DeferredItem<Item> SALMON_STEAK = registerItem(ITEMS, "food/salmon_steak", Item::new, props -> props);
    public static final DeferredItem<Item> SALMON_TEMPURA = registerItem(ITEMS, "food/salmon_tempura", Item::new, props -> props);
    public static final DeferredItem<Item> SASHIMI_PLATTER = registerItem(ITEMS, "food/sashimi_platter", Item::new, props -> props);
    public static final DeferredItem<Item> SCARLET_DEVIL_CAKE = registerItem(ITEMS, "food/scarlet_devil_cake", Item::new, props -> props);
    public static final DeferredItem<Item> SCHOLARS_GINKGO = registerItem(ITEMS, "food/scholars_ginkgo", Item::new, props -> props);
    public static final DeferredItem<Item> SCONE = registerItem(ITEMS, "food/scone", Item::new, props -> props);
    public static final DeferredItem<Item> SCRUMPTIOUS_STORM = registerItem(ITEMS, "food/scrumptious_storm", Item::new, props -> props);
    public static final DeferredItem<Item> SEA_URCHIN_SASHIMI = registerItem(ITEMS, "food/sea_urchin_sashimi", Item::new, props -> props);
    public static final DeferredItem<Item> SEAFOOD_MISO_SOUP = registerItem(ITEMS, "food/seafood_miso_soup", Item::new, props -> props);
    public static final DeferredItem<Item> SECRET_DRIED_FISH_CRISPS = registerItem(ITEMS, "food/secret_dried_fish_crisps", Item::new, props -> props);
    public static final DeferredItem<Item> SECRET_SAVORY_MUSHROOM_HOTPOT = registerItem(ITEMS, "food/secret_savory_mushroom_hotpot", Item::new, props -> props);
    public static final DeferredItem<Item> SEVEN_COLORED_YOKAN = registerItem(ITEMS, "food/seven_colored_yokan", Item::new, props -> props);
    public static final DeferredItem<Item> SHIRAYUKI = registerItem(ITEMS, "food/shirayuki", Item::new, props -> props);
    public static final DeferredItem<Item> SHRIMP_STUFFED_PUMPKIN = registerItem(ITEMS, "food/shrimp_stuffed_pumpkin", Item::new, props -> props);
    public static final DeferredItem<Item> SICHUAN_BOILED_FISH = registerItem(ITEMS, "food/sichuan_boiled_fish", Item::new, props -> props);
    public static final DeferredItem<Item> SMOKED_BUCCANEER = registerItem(ITEMS, "food/smoked_buccaneer", Item::new, props -> props);
    public static final DeferredItem<Item> STAR_LOTUS_SHIP = registerItem(ITEMS, "food/star_lotus_ship", Item::new, props -> props);
    public static final DeferredItem<Item> STEAMED_EGG_BAMBOO_SHOOTS = registerItem(ITEMS, "food/steamed_egg_bamboo_shoots", Item::new, props -> props);
    public static final DeferredItem<Item> STINKY_TOFU = registerItem(ITEMS, "food/stinky_tofu", Item::new, props -> props);
    public static final DeferredItem<Item> SUPREME_SEAFOOD_NOODLES = registerItem(ITEMS, "food/supreme_seafood_noodles", Item::new, props -> props);
    public static final DeferredItem<Item> TAKOYAKI = registerItem(ITEMS, "food/takoyaki", Item::new, props -> props);
    public static final DeferredItem<Item> TANGYUAN = registerItem(ITEMS, "food/tangyuan", Item::new, props -> props);
    public static final DeferredItem<Item> TEMPURA_PLATTER = registerItem(ITEMS, "food/tempura_platter", Item::new, props -> props);
    public static final DeferredItem<Item> TIANSHIS_STEWED_MUSHROOMS = registerItem(ITEMS, "food/tianshis_stewed_mushrooms", Item::new, props -> props);
    public static final DeferredItem<Item> TOFU_STEW = registerItem(ITEMS, "food/tofu_stew", Item::new, props -> props);
    public static final DeferredItem<Item> TOMATO_FRIES = registerItem(ITEMS, "food/tomato_fries", Item::new, props -> props);
    public static final DeferredItem<Item> TONKOTSU_RAMEN = registerItem(ITEMS, "food/tonkotsu_ramen", Item::new, props -> props);
    public static final DeferredItem<Item> TOON_PANCAKE = registerItem(ITEMS, "food/toon_pancake", Item::new, props -> props);
    public static final DeferredItem<Item> TWO_FLAVOR_BEEF_HOTPOT = registerItem(ITEMS, "food/two_flavor_beef_hotpot", Item::new, props -> props);
    public static final DeferredItem<Item> UDUMBARA_CAKE = registerItem(ITEMS, "food/udumbara_cake", Item::new, props -> props);
    public static final DeferredItem<Item> UNCONSCIOUS_YOUKAI_MOUSSE = registerItem(ITEMS, "food/unconscious_youkai_mousse", Item::new, props -> props);
    public static final DeferredItem<Item> UNZAN_COTTON_CANDY = registerItem(ITEMS, "food/unzan_cotton_candy", Item::new, props -> props);
    public static final DeferredItem<Item> URCHIN_RAINDROP_CAKE = registerItem(ITEMS, "food/urchin_raindrop_cake", Item::new, props -> props);
    public static final DeferredItem<Item> URCHIN_STEAMED_EGG = registerItem(ITEMS, "food/urchin_steamed_egg", Item::new, props -> props);
    public static final DeferredItem<Item> VEGETABLE_SALAD = registerItem(ITEMS, "food/vegetable_salad", Item::new, props -> props);
    public static final DeferredItem<Item> WHITE_DEER_UNYIELDING_PINE = registerItem(ITEMS, "food/white_deer_unyielding_pine", Item::new, props -> props);
    public static final DeferredItem<Item> YASHOUMA_DANGO = registerItem(ITEMS, "food/yashouma_dango", Item::new, props -> props);

}
